### ISSUE TITLE
I can't link mineserver bin :(

### ISSUE THREAD

**Issue by timatooth** [Mineserver/mineserver2#4]
Im new to the c++ business and linking stuff has proven pretty frustrating.

I'm using MacOS 10.6 with gcc (i686-apple-darwin10-g++-4.2.1)
cmake version 2.8.5
doxygen-1.7.5.1
latest libnoise from git.
libevent

the mineserver source is cloned from your main branch
Linking CXX executable bin/mineserver
Undefined symbols:
  "_iconv", referenced from:
      Mineserver::Network_Protocol_Notch_PacketStream::operator>>(std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)in packetstream.cpp.o
      Mineserver::Network_Protocol_Notch_PacketStream::operator<<(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)in packetstream.cpp.o
  "_iconv_close", referenced from:
      Mineserver::Network_Protocol_Notch_PacketStream::~Network_Protocol_Notch_PacketStream()in app.cpp.o
      Mineserver::Network_Protocol_Notch_PacketStream::~Network_Protocol_Notch_PacketStream()in app.cpp.o
  "_iconv_open", referenced from:
      Mineserver::Network_Protocol_Notch_PacketStream::Network_Protocol_Notch_PacketStream()in app.cpp.o
      Mineserver::Network_Protocol_Notch_PacketStream::Network_Protocol_Notch_PacketStream()in app.cpp.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make[2]: **\* [bin/mineserver] Error 1
make[1]: **\* [CMakeFiles/mineserver.dir/all] Error 2
make: **\* [all] Error 2

**Comment by deoxxa** [comment]
Should be fixed as of 41b00f9fab
