### ISSUE TITLE
Can't run mineserver2 after make

### ISSUE THREAD

**Issue by fermuch** [Mineserver/mineserver2#8]
I tried to use cmake and make, and I have no errors, but I can't run the mineserver executable.

user@Nunix-Netbook:~/Downloads/mineserver2$ cmake .
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.40.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   signals
--   thread
-- Found ZLIB: /usr/lib/libz.so
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: /usr/lib/libc.so
-- Looking for include files CMAKE_HAVE_PTHREAD_H
-- Looking for include files CMAKE_HAVE_PTHREAD_H - found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found NOISE: /usr/lib/libnoise.so
-- Target: mineserver
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Downloads/mineserver2
user@Nunix-Netbook:~/Downloads/mineserver2$ make
Scanning dependencies of target mineserver
[  1%] Building CXX object CMakeFiles/mineserver.dir/src/app.cpp.o
[  2%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/nbt.cpp.o
[  4%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/game.cpp.o
[  5%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/game/player.cpp.o
[  6%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/localization.cpp.o
[  8%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/server.cpp.o
[  9%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/client.cpp.o
/home/user/Downloads/mineserver2/src/mineserver/network/client.cpp: In member function ‘void Mineserver::Network_Client::write()’:
/home/user/Downloads/mineserver2/src/mineserver/network/client.cpp:118: warning: format ‘%lu’ expects type ‘long unsigned int’, but argument 2 has type ‘size_t’
/home/user/Downloads/mineserver2/src/mineserver/network/client.cpp: In member function ‘void Mineserver::Network_Client::handleWrite(const boost::system::error_code&, size_t)’:
/home/user/Downloads/mineserver2/src/mineserver/network/client.cpp:170: warning: format ‘%lu’ expects type ‘long unsigned int’, but argument 2 has type ‘size_t’
/home/user/Downloads/mineserver2/src/mineserver/network/client.cpp:170: warning: format ‘%lu’ expects type ‘long unsigned int’, but argument 3 has type ‘size_t’
[ 10%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/world/generator/flatlands.cpp.o
[ 12%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/protocol.cpp.o
[ 13%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packetstream.cpp.o
[ 15%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x00.cpp.o
[ 16%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x01.cpp.o
[ 17%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x02.cpp.o
[ 19%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x03.cpp.o
[ 20%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x04.cpp.o
[ 21%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x05.cpp.o
[ 23%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x06.cpp.o
[ 24%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x07.cpp.o
[ 26%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x08.cpp.o
[ 27%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x09.cpp.o
[ 28%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x0A.cpp.o
[ 30%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x0B.cpp.o
[ 31%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x0C.cpp.o
[ 32%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x0D.cpp.o
[ 34%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x0E.cpp.o
[ 35%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x0F.cpp.o
[ 36%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x10.cpp.o
[ 38%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x11.cpp.o
[ 39%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x12.cpp.o
[ 41%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x13.cpp.o
[ 42%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x14.cpp.o
[ 43%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x15.cpp.o
[ 45%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x16.cpp.o
[ 46%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x17.cpp.o
[ 47%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x18.cpp.o
[ 49%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x19.cpp.o
[ 50%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x1A.cpp.o
[ 52%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x1C.cpp.o
[ 53%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x1D.cpp.o
[ 54%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x1E.cpp.o
[ 56%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x1F.cpp.o
[ 57%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x20.cpp.o
[ 58%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x21.cpp.o
[ 60%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x22.cpp.o
[ 61%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x26.cpp.o
[ 63%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x27.cpp.o
[ 64%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x28.cpp.o
[ 65%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x29.cpp.o
[ 67%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x2A.cpp.o
[ 68%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x2B.cpp.o
[ 69%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x32.cpp.o
[ 71%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x33.cpp.o
[ 72%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x34.cpp.o
[ 73%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x35.cpp.o
[ 75%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x36.cpp.o
[ 76%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x3C.cpp.o
[ 78%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x3D.cpp.o
[ 79%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x46.cpp.o
[ 80%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x47.cpp.o
[ 82%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x64.cpp.o
[ 83%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x65.cpp.o
[ 84%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x66.cpp.o
[ 86%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x67.cpp.o
[ 87%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x68.cpp.o
[ 89%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x69.cpp.o
[ 90%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x6A.cpp.o
[ 91%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x6B.cpp.o
[ 93%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x82.cpp.o
[ 94%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0x83.cpp.o
[ 95%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0xC8.cpp.o
[ 97%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0xC9.cpp.o
[ 98%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0xFE.cpp.o
[100%] Building CXX object CMakeFiles/mineserver.dir/src/mineserver/network/protocol/notch/packet/0xFF.cpp.o
Linking CXX executable bin/mineserver
[100%] Built target mineserver

And if I try to run bin/mineserver, it does nothing.

**Comment by carlbennett** [comment]
Run $ ./bin/mineserver2
Now open minecraft and go to your server by typing in the ip. The port is 25565, or the default minecraft port.

There is no output until the server receives a connection.

**Comment by carlbennett** [comment]
The server now outputs this:

> [carl@carlspc ~]$ ./Documents/mineserver2/bin/mineserver
> Mineserver 2.0
> Server is now waiting for connections.

Confirm you see the same? Enter the following for me:

> $ cd ~/Downloads/mineserver2
> $ git pull
> $ cmake .
> $ make
> $ ./bin/mineserver

Thanks.

**Comment by fermuch** [comment]
Sorry. I had a hard week and I can't try it earlier. Now it prints this:
Mineserver 2.0
Server is now waiting for connections.

That helps a lot if you're new to this server. Thank you a lot!

**Comment by carlbennett** [comment]
Glad it helped! :)
