### ISSUE TITLE
Deoxxa!

### ISSUE THREAD

**Issue by timatooth** [Mineserver/mineserver2#9]
Y U NO COMMIT? :(

**Comment by carlbennett** [comment]
He has been away for quite a while. Last I heard he was in China or Japan (one of the two) for vacation, although he's been on vacation for at least three months now and probably much longer considering his last commit date.

**Comment by timatooth** [comment]
I see that Fador has been commiting to mineserver1 again

**Comment by Justasic** [comment]
Yeah i think he was tired of having so much inactivity and decided to update the source while deoxxa is away..

**Comment by deoxxa** [comment]
Real life has taken over for me, unfortunately. I've got this whole thing where I have to do stuff I don't like and some guy gives me money every month. I think people call it a job. It's totally crap though :(

**Comment by carlbennett** [comment]
Are you sure it's real life taking you over, or you controlling your life? Which is it?
